version: '3.8'

services:
  node1:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"   # Dashboard Node 1
      - "50051:50051" # gRPC Node 1
    volumes:
      - ./data1:/root/data
    networks:
      - aether-net

  node2:
    build: .
    ports:
      - "8082:8080"   # Dashboard Node 2
    volumes:
      - ./data2:/root/data
    networks:
      - aether-net

  node3:
    build: .
    ports:
      - "8083:8080"   # Dashboard Node 3
    volumes:
      - ./data3:/root/data
    networks:
      - aether-net

networks:
  aether-net:
    driver: bridge
